resources:
  containers:
    - container: '4.2.0'
      image: norionomura/swiftlint:swift-4.2.0
    - container: 'nightly'
      image: norionomura/swift:nightly

jobs:
- job: macOS
  pool:
    vmImage: xcode9-macOS10.13
  steps:
  - script: export PATH=/usr/local/opt/llvm/bin:"${PATH}"
  - script: brew update
    displayName: 'updating Homebrew'
  - script: brew install llvm
    displayName: 'installing LLVM from Homebrew'
  - script: swift utils/make-pkgconfig.swift
    displayName: 'building package configuration for LLVM'
  - script: swift build 
    displayName: 'running preliminary build'
  - script: swift test
    displayName: 'running tests'

- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    maxParallel: 10
    matrix:
      swift42:
        containerResource: '4.2.0'
      nightly:
        containerResource: 'nightly'
        swiftlint: 'false'
  container: $[ variables['containerResource'] ]
  steps:
  - bash: |
      export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:"${PKG_CONFIG_PATH}"
      wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7.0 main"
      apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
      apt-get update
      apt-get install -y llvm-7.0 libc++1
    displayName: installing LLVM
  - script: swift utils/make-pkgconfig.swift
  - script: swift test
